"""Adiciona coluna valor_unitario à tabela venda

Revision ID: d0780cca4114
Revises: 
Create Date: 2024-08-09 19:23:13.484048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0780cca4114'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendas')
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('valor_unitario', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.alter_column('modelo',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.alter_column('tamanho',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('cor',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.drop_column('valor')
        batch_op.drop_column('total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venda', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('valor', sa.FLOAT(), nullable=False))
        batch_op.alter_column('cor',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.alter_column('tamanho',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('modelo',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
        batch_op.drop_column('valor_total')
        batch_op.drop_column('valor_unitario')

    op.create_table('vendas',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('modelo', sa.VARCHAR(length=80), nullable=False),
    sa.Column('tamanho', sa.VARCHAR(length=20), nullable=False),
    sa.Column('cor', sa.VARCHAR(length=20), nullable=False),
    sa.Column('quantidade', sa.INTEGER(), nullable=False),
    sa.Column('valor_unitario', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('preco_medio', sa.NUMERIC(precision=10, scale=2), nullable=False),
    sa.Column('data', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
